### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by kmvignesh** [Almoullim/background_location#114] opened 2021-09-03 15:10 UTC
I have updated the project to null-safty. that time i updated the version to
```
background_location: ^0.6.1
permission_handler: ^8.1.4+2
```
Then i started testing the app and found background location tracking notification not showing. Then I downgraded the plugin version to
```
background_location: ^0.5.0
permission_handler: ^6.1.3
```
Now its working. So please check and fix the issue.

**Comment by ambernardino** [comment] 2021-09-04 12:09
On 0.6.1, did you set the android notification?

BackgroundLocation.setAndroidNotification(
	title: "Notification title",
        message: "Notification message",
        icon: "@mipmap/ic_launcher",
);

**Comment by kmvignesh** [comment] 2021-09-04 16:56
yes I did. but I am using await keyword before that. I saw some where asked to change the icon. So I tried using other icon also. Still didn't work. Same code is working with 0.5.0

**Comment by jesussmile** [comment] 2021-11-25 07:17
same notification not working for me too..

**Comment by MoralCode** [comment] 2023-07-21 02:49
Is this still an issue?

**Comment by MoralCode** [comment] 2023-07-21 03:03
may be related to #147

**Comment by Almoullim** [comment] 2023-07-25 08:22
fixed in https://github.com/Almoullim/background_location/commit/52ef3db3e572596bb0e879dc57aa201fe160143e version 0.12.0

**Closed by Almoullim** 2023-07-25 08:22 UTC
Labels: needs-testing

**Comment by MoralCode** [comment] 2023-07-25 14:53
@Almoullim did you confirm that this was actually related to notification importance? it definitely seems plausible but idk if theres enough info in the original PR to know for sure

**Comment by Almoullim** [comment] 2023-07-26 10:24
@MoralCode  if not fixed in 0.12 then its a duplicate of https://github.com/Almoullim/background_location/issues/131, no point in keeping in open.
