### ISSUE TITLE
Add time filter similar to distance filter

### ISSUE THREAD

**Issue by bambinoua** [Almoullim/background_location#170] opened 2022-10-19 06:53 UTC
It is good to have a `durationFiltee` similar to `distanceFilter` in method `startLocationService`. Sometimes it is necessary to track geo position using not distance but duration (or even both of them).

**Comment by MoralCode** [comment] 2023-07-21 02:47
closing as duplicate of older issue #142

**Closed by MoralCode** 2023-07-21 02:47 UTC
Labels: duplicate
