### ISSUE TITLE
Conflict between BackgroundLocation.getLocationUpdates and FirebaseMessaging.onBackgroundMessage

### ISSUE THREAD

**Issue by SimonTellier** [Almoullim/background_location#182] opened 2023-02-20 15:47 UTC
Hi,
I am working on exporting my application to Android. Everything I'm going to say next works fine on iOS.

I'm looking for a way to get both services working in the background. (BackgroundLocation.getLocationUpdates and FirebaseMessaging.onBackgroundMessage)
When I run both services in the background, I only have FirebaseMessaging.onBackgroundMessage working.

When I run only BackgroundLocation.getLocationUpdates, the service works fine.

I would like to run both at the same time. Do you have any idea what is going on?

**Comment by sokheangret** [comment] 2023-06-12 01:45
Hi, I'm facing with this issue too. Are there any solution? Thanks.

**Comment by MoralCode** [comment] 2023-07-18 19:15
Are there any associated logs that you see when you try to run both at the same time?

**Comment by MoralCode** [comment] 2023-07-21 02:43
Closing as duplicate of https://github.com/Almoullim/background_location/issues/139

**Closed by MoralCode** 2023-07-21 02:43 UTC
Labels: duplicate
