### ISSUE TITLE
getLocationUpdates is conflicting with firebase onBackgroundMessage in version 0.7.0 or higher

### ISSUE THREAD

**Issue by joesilvams** [Almoullim/background_location#139] opened 2021-12-15 20:13 UTC
I've tested it with all versions from 0.7.0 and none of the BackgroundLocation.getLocationUpdates method provided location.

is conflicting with -> FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

if I comment out that line from firebase, the lib works. If you keep the line, it doesn't work. In version 0.6.0, it worked with this firebase implementation.

Need some extra configuration?

**Comment by sinticbolivia** [comment] 2021-12-20 13:52
same error here, it does not works with firebase

**Comment by Almoullim** [comment] 2023-07-26 10:26
duplicate of **https://github.com/Almoullim/background_location/issues/131**

**Closed by Almoullim** 2023-07-26 10:26 UTC
