### ISSUE TITLE
BackgroundLocation.getLocationUpdates don't work

### ISSUE THREAD

**Issue by qcuong97** [Almoullim/background_location#145] opened 2022-02-11 09:14 UTC
I use 0.8.1 it not work, but it's work with 0.6.0
----------------------
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.18363.1556], locale vi-VN)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

**Comment by KamilSvoboda** [comment] 2022-02-15 12:45
In my case it doesn't work in combination with Firebase Messaging initialization `FirebaseMessaging.onBackgroundMessage`

**Comment by KarimAbdo** [comment] 2022-02-28 11:40
@KamilSvoboda this drove me crazy. did you manage to find a work around ?

**Comment by KamilSvoboda** [comment] 2022-02-28 19:35
> @KamilSvoboda this drove me crazy. did you manage to find a work around ?

Unfortunately not. :( I'm waiting for response of the plugin author.

**Comment by jesussmile** [comment] 2022-03-03 10:26
Damn!  Mine too. Any suggestions for other plugins ?

**Comment by KarimAbdo** [comment] 2022-03-09 20:50
@jesussmile, i have my eye on https://pub.dev/packages/geolocation but haven't tried it yet

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:58
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:59
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by rsbthebest** [comment] 2022-04-04 07:59
Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

**Comment by qcuong97** [comment] 2022-04-04 08:34
> Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??

You should use v0.7.0, it's not be error

**Comment by jesussmile** [comment] 2022-04-05 03:51
> > Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??
> 
> You should use v0.7.0, it's not be error

following your advice, I downgraded but keep running into this error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by qcuong97** [comment] 2022-04-05 04:05
> > > Bumping this up, am facing the same issue on Android. Is it linked to FirebaseMessaging.onBackgroundMessage??
> > 
> > 
> > You should use v0.7.0, it's not be error
> 
> following your advice, I downgraded but keep running into this error
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':background_location:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> ```

You try run android native source for debug error
My infor:
Kotlin version: 1.6.10
Gradle:4.1.0

**Comment by rsbthebest** [comment] 2022-04-06 06:50
Hi Team,

V 0.7.0 won't work on Android 12 because of this error:

Unable to create service com.almoullim.background_location.LocationUpdatesService: java.lang.IllegalArgumentException: uk.co.walkwithyou.walkwithyou: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

So can't use it.

**Comment by rsbthebest** [comment] 2022-04-06 06:50
Hi Team,

V 0.7.0 won't work on Android 12 because of this error:

Unable to create service com.almoullim.background_location.LocationUpdatesService: java.lang.IllegalArgumentException: uk.co.walkwithyou.walkwithyou: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

So can't use it.

**Comment by rsbthebest** [comment] 2022-04-07 07:32
Removing "FirebaseMessaging.onBackgroundMessage" fixed it, but we need a real solution which can help us use  FirebaseMessaging.onBackgroundMessage with this plugin.

**Comment by rsbthebest** [comment] 2022-04-07 07:32
Removing "FirebaseMessaging.onBackgroundMessage" fixed it, but we need a real solution which can help us use  FirebaseMessaging.onBackgroundMessage with this plugin.

**Comment by jesussmile** [comment] 2022-04-07 07:44
Why don't you use Background locator plugin instead . It works fine.

**Comment by rsbthebest** [comment] 2022-04-07 07:56
Because this is not a blocker for me as of now, so I this plugin is fixed am happy to continue using it.

**Comment by MoralCode** [comment] 2023-07-21 02:40
@qcuong97 were you also trying to use firebase when encountering this originally?

if so lets use #139 as the canonical issue for this problem

**Comment by qcuong97** [comment] 2023-07-21 02:42
> 

Yes, it my problem so i used Geolocator

**Comment by MoralCode** [comment] 2023-07-21 02:44
gotcha, in that case, closing this as a duplicate of #139 to consolidate everything into one issue

**Closed by MoralCode** 2023-07-21 02:44 UTC
