### ISSUE TITLE
Version 0.9.0 not available on pub.dev

### ISSUE THREAD

**Issue by seo345** [Almoullim/background_location#176] opened 2023-01-19 08:50 UTC
Is it possible to pubblish the latest version on pub.dev?

I really need it

**Comment by jannisnikoy** [comment] 2023-01-27 20:22
@seo345 I had the same issue due to the build errors on Android; I worked around it by replacing the pub spec entry with:

`  background_location:
    git:
      url: https://github.com/Almoullim/background_location
      ref: master
    `

**Comment by seo345** [comment] 2023-01-30 08:02
I know, but I need for an autometed import with my devOps

**Comment by MoralCode** [comment] 2023-06-03 21:50
Looks like the github action for publishing to pub.dev was removed in august 2022 and Ali's profile doesn't seem to have any contributions since then: https://github.com/Almoullim/background_location/commit/6756c7c974721d5c2bf6894f04f20d2e08dc31b2

**Comment by MoralCode** [comment] 2023-07-18 19:20
Update, I have made a PR to implement the github action in the flutter recommended way (#189)

**Comment by MoralCode** [comment] 2023-07-21 01:44
Closing as duplicate of #166

**Closed by MoralCode** 2023-07-21 01:44 UTC
Labels: duplicate
