### ISSUE TITLE
Wrong notification tile is showing 

### ISSUE THREAD

**Issue by pranavnair183** [Almoullim/background_location#136] opened 2021-11-29 04:52 UTC
I don't know why I am getting this notification tile. I am sure that this happens after the line
`await BackgroundLocation.startLocationService(distanceFilter: 20);` 

![InkedScreenshot_1638160959_LI](https://user-images.githubusercontent.com/89894586/143810430-8af70591-0b04-4d3b-9b5d-698060c6bda1.jpg)

**Comment by jesussmile** [comment] 2021-12-17 07:16
yea same issue any fix yet ?

**Comment by MoralCode** [comment] 2023-07-21 02:28
android requires a notification to be present if you want the location to continue updating in the background

see the [README](https://github.com/Almoullim/background_location/blob/87a6e446e2e08157566fa444295a99cd6c9e26b6/README.md?plain=1#L35) for information on how to customize this notification 

Closing as this appears to be intended behavior

**Closed by MoralCode** 2023-07-21 02:28 UTC
