### ISSUE TITLE
Used for targetSdkVerison 34

### ISSUE THREAD

**Issue by rfahlevi** [Almoullim/background_location#199] opened 2024-02-07 08:53 UTC
How to use this package if my app use targetsSdkVersion 34?

Please help me

**Comment by MoralCode** [comment] 2024-02-07 14:48
Closing as a duplicate of a more detailed issue #200

Given the need for more maintainers in #188 i wouldn't count on anything happening too quickly though.

You're also welcome to submit a pull request if you'd like to update the necessary files to point to current API levels (or ideally, [use whats configured by flutter](https://stackoverflow.com/questions/53977807/flutter-compilesdkversion-and-targetsdkversion-on-android#53977947))

**Closed by MoralCode** 2024-02-07 14:48 UTC
