### ISSUE TITLE
Start location tracking is triggering twice. Any idea how to fix?

### ISSUE THREAD

**Issue by jaca420** [Almoullim/background_location#157] opened 2022-06-15 08:28 UTC
When starting location tracking, the code inside `BackgroundLocation.getLocationUpdates((location) {` is triggered twice. Any idea on how to fix this?

    startLocationTracking() async {
      await BackgroundLocation.setAndroidNotification(
        title: 'Background service is running',
        message: 'Background location in progress',
        icon: '@mipmap/ic_launcher',
      );

      await BackgroundLocation.startLocationService(distanceFilter: 50);

      BackgroundLocation.getLocationUpdates((location) {

          setState(() {
            latitude = location.latitude.toString();
            longitude = location.longitude.toString();
            accuracy = location.accuracy.toString();
            altitude = location.altitude.toString();
            bearing = location.bearing.toString();
            speed = location.speed.toString();
          });
      });
    }

**Comment by tomkcook** [comment] 2022-06-24 18:18
I'm seeing the same.  Starting background location updates like this:

```
    BackgroundLocation.setAndroidNotification(
      title: "MyApp",
      message: "Tracking your location",
      icon: "@mipmap/ic_launcher",
    );
    BackgroundLocation.setAndroidConfiguration(5000).then((p) {
      BackgroundLocation.startLocationService();
      BackgroundLocation.getLocationUpdates((location) {
        print("${location.latitude}, ${location.longitude}");
      });
      return null;
    });
```

I think I should see the location printed once every five seconds.  Actually, I see the location printed twice every second.  So two issues:

- `setAndroidConfiguration` appears to be ignored.
- `getLocationUpdates` seems to register the listener twice, resulting in double delivery of events.

**Comment by jaca420** [comment] 2022-06-30 10:48
I fixed this by adding a `running` variable in the widget. I set it `true` when location updates, save the location to Firestore then set it `false`. Return in my processing function if it's set to true. I didn't want multiple writes to database. 

void processLocation(location) async {
      if (running) return;
      running = true;

      //update location
      await ... save data to Firestore

      Future.delayed(
        const Duration(seconds: 25),
        () => running = false,
      );
    }

**Comment by dJani97** [comment] 2022-09-10 16:38
I came up with a similar solution using the [mutex](https://pub.dev/packages/mutex) package.
```dart
final lock = Mutex();

const interval = 5000;
const halfInterval = Duration(milliseconds: interval ~/ 2);

await BackgroundLocation.setAndroidConfiguration(interval);
await BackgroundLocation.startLocationService();
BackgroundLocation.getLocationUpdates((location) {

  if (lock.isLocked) return;

  lock.protect(() {
    print(location.toMap().toString());
    return Future.delayed(halfInterval);
  });

});
```

`lock = Mutex()` creates a lock

`lock.protect(() {  })` ensures that the code within can only be executed once at a time

`if (lock.isLocked) return;` catches parallel executions and immediately returns

Since printing the state is too fast, I'm artificially prolonging the event processing time by using `Future.delayed(halfInterval)`.

This ensures that no further events can be processed within the first half of the interval.

**Comment by xortuna** [comment] 2023-06-14 21:19
There's a much simpler way of filtering these without any async or timers:

```dart
double? _lastLocationTime;
BackgroundLocation.getLocationUpdates((location) {
  if (_lastLocationTime == location.time) {
    //Duplicate Location filtered
    return;
  }
  _lastLocationTime = location.time;
  //Normal processing here
}
```

**Comment by MoralCode** [comment] 2023-07-21 03:12
this seems like an implementation/duplicate of #10

**Closed** 2023-07-24 11:49 UTC
Labels: duplicate
