### ISSUE TITLE
crash above android 14 (34)

### ISSUE THREAD

**Issue by nimesh519** [Almoullim/background_location#229] opened 2024-12-05 13:41 UTC
When opening with using this pluggin hen page is crashed due to lack of run time permission for android 14  if addded background location permission at manifest and runtime then I think issue can resolve , I have already tried with  same code plz update pluggin

**Comment by MoralCode** [comment] 2024-12-05 19:14
Seems like a Duplicate of #200

**Closed by MoralCode** 2024-12-05 19:14 UTC
