### ISSUE TITLE
background location not updating dynamically

### ISSUE THREAD

**Issue by monikamishra-54** [Almoullim/background_location#187] opened 2023-05-08 11:35 UTC
When I click on "start service" and then click on "current location" It shows my current location and time but when I change my location it dosen't update on UI.

**Comment by MoralCode** [comment] 2023-07-18 19:09
Are you seeing a specific error message in the logs when the location doesnt update like you expect?

**Comment by MoralCode** [comment] 2023-07-21 03:03
may be related to #147

**Comment by MoralCode** [comment] 2023-07-22 16:34
closing as duplicate of #156

**Closed by MoralCode** 2023-07-22 16:34 UTC
Labels: duplicate
